name: ci

on:
  push:
    branches: [master]
  release:
    types: [created]
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/standard-build.yaml
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
      actions: read
      security-events: write
    with:
      # can't use the default "ghcr.io/${{ github.repository }}" since
      # "ghcr.io/miracum/.github:pr-1": invalid reference format"
      image: ghcr.io/miracum/github-reusable-workflow
      enable-build-test-layer: true
      enable-upload-test-image: true
      platforms: linux/amd64,linux/arm64
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build-without-test-image:
    uses: ./.github/workflows/standard-build.yaml
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
      actions: read
      security-events: write
    with:
      image: ghcr.io/miracum/github-reusable-workflow-without-test-image
      enable-build-test-layer: false
      enable-upload-test-image: false
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build-with-fixed-image-tags:
    uses: ./.github/workflows/standard-build.yaml
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
      actions: read
      security-events: write
    with:
      image: ghcr.io/miracum/github-reusable-workflow-with-fixed-image-tags
      enable-build-test-layer: true
      enable-upload-test-image: true
      image-tags: |
        type=semver,pattern={{raw}},value=v1.2.3-beta.123
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    uses: ./.github/workflows/standard-lint.yaml
    permissions:
      contents: read
      pull-requests: write
      issues: write
      security-events: write
      actions: read
    with:
      codeql-languages: '["python"]'
      enable-codeql: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - name: Download build image
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: ${{ needs.build.outputs.image-slug }}
          path: /tmp

      - name: Download test image
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: ${{ needs.build.outputs.image-slug }}-test
          path: /tmp

      - name: ls
        run: |
          echo ""${{ needs.build.outputs.image-tags }}""
          ls -lsa /tmp

      - name: Install regctl
        uses: regclient/actions/regctl-installer@35bc5829dd3d37ace2717971f3151894b43bfabc

      - name: load image
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          regctl image import "${{ needs.build.outputs.image-tags[0] }}" /tmp/image.tar
          regctl image import "${{ needs.build.outputs.test-image-tags[0] }}" /tmp/image-test.tar

      - name: load image
        run: |
          docker image ls

  release:
    uses: ./.github/workflows/standard-release.yaml
    needs:
      - build
      - test
    permissions:
      contents: write
      pull-requests: write
      issues: write
    secrets:
      semantic-release-token: ${{ secrets.GITHUB_TOKEN }}
