name: scheduled

on:
  repository_dispatch: {}
  workflow_dispatch: {}
  # only to test the workflow as part of PRs
  pull_request:
    branches:
      - master
  schedule:
    - cron: "00 18 * * *"

permissions: read-all

jobs:
  schedule:
    uses: ./.github/workflows/standard-schedule.yaml
    permissions:
      contents: read
      issues: write
      security-events: write
    with:
      images: "['ghcr.io/miracum/github-reusable-workflow:master', 'ghcr.io/miracum/github-reusable-workflow:master']"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
