name: Standard workflow for linting

permissions:
  contents: read

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      enable-codeql:
        description: "Enable CodeQL analysis"
        required: false
        default: true
        type: boolean
      codeql-languages:
        description: "Languages to run CodeQL analysis for. CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]"
        required: false
        default: '["java", "csharp", "python"]'
        type: string
      enable-validate-gradle-wrapper:
        description: "Enable Gradle wrapper validation"
        required: false
        default: true
        type: boolean
      enable-verify-base-image-signature:
        description: "Enable Dockerfile base image validation"
        required: false
        default: true
        type: boolean
      verify-base-image-certificate-oidc-issuer:
        description: "The OIDC issuer for the cosign base image signature"
        required: false
        default: "https://accounts.google.com"
        type: string
      verify-base-image-certificate-identity:
        description: "The certificate identity for the cosign base image signature"
        required: false
        default: "keyless@distroless.iam.gserviceaccount.com"
        type: string
    secrets:
      github-token:
        description: "The GitHub workflow token used to push to ghcr.io. Also used by MegaLinter"
        required: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # MegaLinter
      - name: MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.io/latest/flavors/
        uses: oxsecurity/megalinter@b48455a119cc28045eee8f1e9d0a542a85e71f4f # v7.5.0
        env:
          VALIDATE_ALL_CODEBASE: "true"
          GITHUB_TOKEN: ${{ secrets.github-token }}

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log

  dependency-review:
    name: dependency review
    runs-on: ubuntu-22.04
    # can only run on PRs or the error is:
    # "Both a base ref and head ref must be provided, either via the `base_ref`/`head_ref` config options, or by running a `pull_request`/`pull_request_target` workflow."
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Dependency Review
        uses: actions/dependency-review-action@6c5ccdad469c9f8a2996bfecaec55a631a347034 # v3.1.0

  gradle-wrapper-validation:
    name: validate gradle wrapper
    runs-on: ubuntu-22.04
    if: ${{ inputs.enable-validate-gradle-wrapper }}
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0

  base-image-signature-verification:
    name: validate Dockerfile base image signature
    runs-on: ubuntu-22.04
    if: ${{ inputs.enable-verify-base-image-signature }}
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 1
      - name: Install Cosign
        uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # v3.1.2
      - run: |
          cosign dockerfile verify \
            --output text \
            --base-image-only \
            --certificate-oidc-issuer ${{ inputs.verify-base-image-certificate-oidc-issuer }} \
            --certificate-identity ${{ inputs.verify-base-image-certificate-identity }} \
            Dockerfile

  codeql-analyze:
    name: CodeQL analyze
    runs-on: ubuntu-22.04
    if: ${{ inputs.enable-codeql }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJSON(inputs.codeql-languages) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Java
        if: ${{ matrix.language == 'java' }}
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@49abf0ba24d0b7953cb586944e918a0b92074c80 # v2.22.4
        with:
          languages: ${{ matrix.language }}
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.

          # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
          queries: +security-extended,security-and-quality

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: Autobuild
        uses: github/codeql-action/autobuild@49abf0ba24d0b7953cb586944e918a0b92074c80 # v2.22.4

      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

      #   If the Autobuild fails above, remove it and uncomment the following three lines.
      #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.

      # - run: |
      #   echo "Run, Build Application using script"
      #   ./location_of_script_within_repo/buildscript.sh

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@49abf0ba24d0b7953cb586944e918a0b92074c80 # v2.22.4
        with:
          category: "/language:${{matrix.language}}"
